### ISSUE TITLE
600mm Karl-Gerat Unlock under 9 Inch Howitzer Research

### ISSUE THREAD

**Issue by violetsamber** [Faryzal2020/DefinitelyMoreCannons#5]
I have not researched the 600mm gun but I can build it.

Visual with the ResearchPal research tree.
![image](https://user-images.githubusercontent.com/31017076/52838924-2af7cd00-30a9-11e9-925d-588042bdf98f.png)

**Comment by violetsamber** [comment]
in the Turret_60cm.xml

```
<researchPrerequisites>
      <li>mark1howitzer</li>
</researchPrerequisites>
```

should be

```
<researchPrerequisites>
      <li>KarlGerat</li>
</researchPrerequisites>
```

PullRequest #9

![image](https://user-images.githubusercontent.com/31017076/52842663-a8750a80-30b4-11e9-9b29-2231ec83a976.png)

**Comment by Faryzal2020** [comment]
thanks i've merged your pull request for this
