### ISSUE TITLE
9.2 inch howitzer shells naming inconsistant with cannon name

### ISSUE THREAD

**Issue by violetsamber** [Faryzal2020/DefinitelyMoreCannons#6]
I have the research completed but the shells are not showing up.

![image](https://user-images.githubusercontent.com/31017076/52839399-e10fe680-30aa-11e9-940e-591d8fce84ce.png)

**Comment by violetsamber** [comment]
I just looked at the def for the 9.2inch gun and saw that it actually uses the 288mmShells.
Looks like you where in process of renaming the gun to use mm instead of inches.

**Comment by Faryzal2020** [comment]
the gun is actually 9.2 Inch because its a french-made. but in the defName, a dot (.) is not allowed, 9.2 Inch equals 288mm, so i named it 288mm. but yeah i should've been consistent and only use the 288mm in the defName instead of on random tags.

i've renamed the label of the recipe to 9.2 Inch
