### ISSUE TITLE
Howitzers' unable to shoot over walls

### ISSUE THREAD

**Issue by violetsamber** [Faryzal2020/DefinitelyMoreCannons#7]
Direct line of sight the cannon can shoot but over walls it cannot target a location.

![image](https://user-images.githubusercontent.com/31017076/52839806-27197a00-30ac-11e9-89b9-acfee5cfb882.png)

![image](https://user-images.githubusercontent.com/31017076/52839833-3a2c4a00-30ac-11e9-8268-059d3e429b69.png)

**Comment by violetsamber** [comment]
In the ThingDefs\Cannons_H\Turret_15cm.xml it has <requireLineOfSight>true</requireLineOfSight>
changing that to false allows the gun to shoot over walls

**Comment by randevlper** [comment]
#

**Comment by violetsamber** [comment]
Woops did not mean to close this.
 I made a pull request with the fix.
#8

**Comment by Faryzal2020** [comment]
thanks i've merged the pull request
